name: create release

on:
    release:
      types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install the latest version of rye
              uses: eifinger/setup-rye@v3

            - name: Sync rye
              run: rye sync
            
            - name: Build
              run: rye build && ls
            
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: |
                 dist/*.whl
                 dist/*.tar.gz